# Generated by Django 5.1 on 2024-08-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('Cliente', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=20)),
                ('TipoConsulta', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=50)),
                ('DescripcionConsulta', models.TextField()),
                ('Direccion', models.CharField(max_length=255)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
