# Generated by Django 5.1 on 2024-08-19 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='external_id',
        ),
    ]
