# Generated by Django 5.1 on 2024-08-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_remove_consulta_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='airtable_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
